# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = "generic/debian12"
    wordpress.vm.provision :"shell", path: "wordpress.sh"
  end

#  https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces
#  config.vm.network "private_network", ip: "192.168.56.76"
  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder ".", "/vagrant"
end
