# https://wiki.debian.org/VirtualBox#Debian_10_.22Buster.22_and_Debian_11_.22Bullseye.22
-
  name: Virtualbox installation
  hosts: localhost
  become: yes
  tasks:
    - name: Fasttrack for Virtualbox
      apt:
        name: fasttrack-archive-keyring
        state: present
    - name: Add bullseye-fasttrack to fasttrack.list
      lineinfile:
        path: /etc/apt/sources.list.d/fasttrack.list
        line: deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
        create: yes
    - name: Add bullseye-backports-staging to fasttrack.list
      lineinfile:
        path: /etc/apt/sources.list.d/fasttrack.list
        line: deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
        create: yes
    - name: Update and upgrade apt packages
      apt:
        name: "*"
        state: latest
        update_cache: yes
    - name: Install virtualbox
      apt:
        name: virtualbox
        state: present
